Document: cframp3
Title: Debian cframp3 Manual
Author: <insert document author here>
Abstract: This manual describes what cframp3 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cframp3/cframp3.sgml.gz

Format: postscript
Files: /usr/share/doc/cframp3/cframp3.ps.gz

Format: text
Files: /usr/share/doc/cframp3/cframp3.text.gz

Format: HTML
Index: /usr/share/doc/cframp3/html/index.html
Files: /usr/share/doc/cframp3/html/*.html
